[project]
name = "uk_local_authority_names_and_codes"
version = "0.1.0"
description = "uk_local_authority_names_and_codes"
requires-python = ">=3.10,<3.15"
dependencies = [
    "beautifulsoup4>=4.12",
    "data-common[dataset]",
    "htmltabletomd>=1.0",
    "ipykernel>=6",
    "nbconvert>=7",
    "nbformat>=5",
    "pandas>=2.2",
    "rich>=13.7",
    "rich-click>=1.8",
    "traitlets>=5.14",
]

[project.scripts]
project = "uk_local_authority_names_and_codes.__main__:main"

[dependency-groups]
test = [
    "pytest>=8",
]
lint = [
    "ruff>=0.6.1",
]
type = [
    "pandas-stubs>=2.2",
    "pyright>=1.1.248",
]
notebook = [
    "data-common[notebook]",
    "jupyterlab>=4",
]
render = [
    "data-common[render]",
]
google = [
    "data-common[google]",
]
dev = [
    { include-group = "test" },
    { include-group = "lint" },
    { include-group = "type" },
]

[tool.uv]
[tool.uv.sources]
data-common = { path = "src/data_common/", editable = true }

[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"

[tool.pyright]
include = ["src", "notebooks"]
exclude=["src/data_common"]
typeCheckingMode="basic"
reportPrivateImportUsage="warning"

[notebook.settings]
default_page_title = "Settings file defined title"

[tool.dataset]
dataset_dir = "data/packages"
publish_dir = "docs/"
publish_url = "https://pages.mysociety.org/uk_local_authority_names_and_codes/datasets/"
credit_text = "If you find this data useful, please let us know to help us make the case for future funding."
credit_url = "https://survey.alchemer.com/s3/6876792/Data-usage"

[tool.ruff]
extend-exclude = ["migrations", "*.pyi"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"notebooks/*.ipynb" = ["F403", "F405"]
"tests/*.py" = ["E712"]

[tool.ruff.lint.isort]
known-first-party = ["hub"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
