name: Build datasets

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
on:
  push: 
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo content
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: 'recursive'
          
      - name: Run tests and try and build project
        uses: ./.github/actions/in-dev-container
        with:
          run: |
            script/test
            dataset build --all
            dataset version auto --auto-ban major --all --publish
            
      - name: Push new data
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "Update repo data based on source changes"