name: 'Run command in dev-container'
description: 'Run a series of commands inside the default devcontainer'
inputs:
  run: 
    description: 'Commands to run inside context'
    required: true
  shell: 
    description: 'shell to run command on inside docker'
    default: 'bash --noprofile --norc -eo pipefail'
  app: 
    description: 'docker-compose app to run command in'
    required: true
    default: 'app'

runs:
  using: "composite"

  steps:
    - name: Build image from docker-compose
      uses: $/.github/actions/cached-build
      with:
        branch: "main"
        dockerfile: Dockerfile
        push_to_registry: false
    
    - name: Run script in docker
      shell: bash
      env:
        DEV_CONTAINER_APP: ${{ inputs.app }}
        DEV_CONTAINER_RUN: ${{ inputs.run }}
        DEV_CONTAINER_SHELL: ${{ inputs.shell }}
      run: |
        read -r -a shell_args <<< "$DEV_CONTAINER_SHELL"
        printf '%s\n' "$DEV_CONTAINER_RUN" | docker compose -f docker-compose.yml run \
          --volume /home/runner:/home/runner/ \
          "$DEV_CONTAINER_APP" "${shell_args[@]}" -s
