#!/bin/bash

echo "get submodule to appear as main rather than latest comment"
cd src/data_common
git checkout main
cd ../..
cd docs/theme
git checkout main

cd ../..
uv sync --group notebook
echo 'eval "$(_DATASET_COMPLETE=bash_source dataset)"' >> ~/.bashrc
