#!/bin/bash

echo "--------------"
echo "Running pytest"
echo "--------------"
uv run pytest
pytestexit=$?
echo "--------------"
echo "Running ruff"
echo "--------------"
uv run ruff check .
ruffcheckexit=$?
uv run ruff format . --check
ruffformatexit=$?
echo "--------------"
echo "Running pyright"
echo "--------------"
uv run pyright
pyrightexit=$?

echo "Pytest status: $pytestexit"
echo "Ruff Check status: $ruffcheckexit"
echo "Ruff Format status: $ruffformatexit"
echo "Pyright status: $pyrightexit"

sum="$(($pytestexit + $pyrightexit + $ruffcheckexit + $ruffformatexit))"

if [ "$sum" != "0" ]; then
    exit 1
else
    exit 0
fi
