theme: jekyll-theme-slate
title: UK Local Authorities
description: Dataset of basic information and ID lookup for UK local authorities.

baseurl: "/uk_local_authority_names_and_codes"
url: "https://mysociety.github.io"

collections:
  datasets:
    output: true
  downloads:
    output: true


defaults:
  - scope:
      path: ""
      type: datasets
    values:
      layout: datasets/dataset
  - scope:
      path: ""
      type: downloads
    values:
      download_gate_type: soft
      download_form_header: Can you help us with funding by telling us more about yourself?
      download_survey: 6876792/Data-usage
      layout: datasets/download
plugins:
  - jekyll-feed

# Twitter
twittercard:
  enabled: true
  username: "@mysociety"

logo: "/theme/img/mysociety-large-social.png"
layouts_dir: theme/_layouts
includes_dir: theme/_includes

sass:
    sass_dir: 
    load_paths:
        - theme/sass
        - sass  


# Exclude these files from the build
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml
  - node_modules
  - scripts/src
  - package.json
  - webpack.config.js
  - README.md